language: php

php:
  - 5.3
  - 5.4

env:
  - MIDGARD=midgard MIDGARD_EXT_VERSION=ratatoskr
  - MIDGARD=midgard MIDGARD_EXT_VERSION=gjallarhorn
  - MIDGARD=nomidgard

before_script:
  - ./tests/travis_${MIDGARD}.sh

script: phpunit --coverage-text

notifications:
    irc: "irc.freenode.org#midgard"
